"use client";

import { useEffect, useMemo, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { useLedger } from "@/lib/LedgerContext";
import { calculateRealCost } from "@/lib/costCalculator";
import providersData from "@/data/providers.json";
import { Provider } from "@/lib/types";
import { PROCEDURES } from "@/lib/procedures";
import Link from "next/link";

function ActionContent() {
  const params = useSearchParams();
  const providerId = params.get("provider") || "";
  const procedureId = params.get("procedure") || "mri-knee";

  const { ledger, amountPaidSoFar, addVisit } = useLedger();
  const providers = providersData as Provider[];
  const provider = providers.find((p) => p.id === providerId);
  const procedure = provider?.procedures[procedureId];
  const procedureMeta = PROCEDURES.find((p) => p.id === procedureId);

  const [letter, setLetter] = useState("");
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [logged, setLogged] = useState(false);

  const breakdown = useMemo(() => {
    if (!procedure) return null;
    return calculateRealCost(procedure.stickerPrice, amountPaidSoFar, ledger.insurance);
  }, [procedure, amountPaidSoFar, ledger.insurance]);

  useEffect(() => {
    if (!provider || !procedure || !breakdown) return;
    setLoading(true);
    fetch("/api/letter", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        providerName: provider.name,
        procedureName: procedure.name,
        cptCode: procedure.cptCode,
        yourCost: breakdown.yourCost,
        stickerPrice: procedure.stickerPrice,
        address: provider.address,
      }),
    })
      .then((res) => res.json())
      .then((data) => setLetter(data.letter || ""))
      .finally(() => setLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [providerId, procedureId]);

  if (!provider || !procedure || !breakdown || !procedureMeta) {
    return (
      <div className="card p-6">
        <p>Provider or procedure not found.</p>
        <Link href="/search" className="btn-primary inline-block mt-4">
          Back to search
        </Link>
      </div>
    );
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(letter);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const handleLogVisit = () => {
    addVisit({
      date: new Date().toISOString().slice(0, 10),
      procedure: procedure.name,
      provider: provider.name,
      amountPaid: breakdown.yourCost,
    });
    setLogged(true);
  };

  return (
    <div>
      <div className="mb-4">
        <h1 className="text-2xl font-bold mb-1">You&apos;re all set</h1>
        <p style={{ color: "var(--color-muted)" }}>
          Here&apos;s your cost summary and a message you can send before booking.
        </p>
      </div>

      <div className="card p-5 mb-4">
        <h2 className="font-semibold text-lg mb-1">{provider.name}</h2>
        <p className="text-sm mb-3" style={{ color: "var(--color-muted)" }}>
          {procedure.name} · CPT {procedure.cptCode} · {provider.address}
        </p>
        <div className="grid grid-cols-3 gap-3 text-center">
          <div className="p-3 rounded-xl" style={{ background: "#f7f8fa" }}>
            <p className="text-xs" style={{ color: "var(--color-muted)" }}>
              Sticker price
            </p>
            <p
              className="text-lg font-semibold"
              style={{ textDecoration: "line-through", color: "var(--color-muted)" }}
            >
              ${breakdown.stickerPrice.toLocaleString()}
            </p>
          </div>
          <div className="p-3 rounded-xl" style={{ background: "#e6f4f4" }}>
            <p className="text-xs" style={{ color: "var(--color-primary)" }}>
              Your cost
            </p>
            <p className="text-lg font-bold" style={{ color: "var(--color-primary)" }}>
              ${breakdown.yourCost.toLocaleString()}
            </p>
          </div>
          <div className="p-3 rounded-xl" style={{ background: "#f7f8fa" }}>
            <p className="text-xs" style={{ color: "var(--color-muted)" }}>
              Insurance covers
            </p>
            <p className="text-lg font-semibold">${breakdown.insuranceCovers.toLocaleString()}</p>
          </div>
        </div>
      </div>

      <div className="card p-5 mb-4">
        <div className="flex items-center justify-between mb-2">
          <h2 className="font-semibold">Cost confirmation message</h2>
          <span className="text-xs" style={{ color: "var(--color-muted)" }}>
            Generated by Grok
          </span>
        </div>
        {loading ? (
          <p className="text-sm" style={{ color: "var(--color-muted)" }}>
            Generating message…
          </p>
        ) : (
          <textarea
            readOnly
            value={letter}
            className="w-full text-sm p-3 rounded-lg border"
            style={{ borderColor: "var(--color-border)", minHeight: 160, background: "#fafafa" }}
          />
        )}
        <div className="flex gap-2 mt-3">
          <button onClick={handleCopy} className="btn-secondary" disabled={loading}>
            {copied ? "Copied!" : "Copy message"}
          </button>
          <button onClick={handleLogVisit} className="btn-primary" disabled={logged}>
            {logged ? "Logged to your ledger ✓" : "Log this visit to my ledger"}
          </button>
        </div>
      </div>

      <div className="flex gap-3">
        <Link href="/search" className="btn-ghost">
          ← Back to search
        </Link>
        <Link href="/" className="btn-ghost">
          Go to ledger
        </Link>
      </div>
    </div>
  );
}

export default function ActionPage() {
  return (
    <Suspense fallback={<div>Loading…</div>}>
      <ActionContent />
    </Suspense>
  );
}
